# Generated by Django 4.0.2 on 2022-03-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('suite', 'Suite Room'), ('standard', 'Standard Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room'), ('luxury', 'Luxury Room'), ('superior', 'Superior Room')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_capacity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('view', models.CharField(max_length=32)),
                ('bed_number', models.IntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('available', models.BooleanField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype')),
            ],
        ),
    ]
